services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: studentmgmtdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  lucee:
    image: lucee/lucee:5.4.0.80-nginx
    environment:
      - VIRTUAL_HOST=dev.studentmgmtapp.com
    volumes:
      - "./:/var/www/"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./password.txt:/opt/lucee/server/lucee-server/context/password.txt"
    ports:
      - "8854:8888"
      - "8054:80"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
